version: "3.9"
services:
  database:
    image: postgres:15
    container_name: database
    ports:
      - "5432:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  postgres-data: